#Python:- Numpy Arrays

In [53]:
import numpy as np

In [54]:
"""
One way to create a numpy array is from an existing object
such as list

"""

'\nOne way to create a numpy array is from an existing object\nsuch as list\n\n'

In [55]:
ls=[1,2,3]
type(ls)

list

In [56]:
# transform this list into an array

np.array(ls)

array([1, 2, 3])

In [57]:
arr=np.array(ls)
arr

array([1, 2, 3])

In [58]:
# Transform a nested list into a numpy array
# which is called matrix


In [59]:
ls=[[1,2,3],[4,5,6],[7,8,9]]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [60]:
mtr=np.array(ls)
mtr
# this is 2D matrix.
# we can check how many dimensions it has, based on the number
# brackets that are shows in the beginning or at the very end
# we have X-axis and Y-axis which makes it 2D matrix.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
mtr.shape
#to check built in methods 1st need to run the mtr object


(3, 3)

**Built in Methods**

In [62]:

"""
Numpy. arange is a function that produces an array of
sequential numbers within a given interval.
It differs from Python's builtin range()
function in that it can handle floating-point
numbers as well as arbitrary step sizes.
Also, the output of numpy.
arange is an array of elements instead of a range object.
"""

"\nNumpy. arange is a function that produces an array of \nsequential numbers within a given interval. \nIt differs from Python's builtin range()\nfunction in that it can handle floating-point \nnumbers as well as arbitrary step sizes.\nAlso, the output of numpy. \narange is an array of elements instead of a range object.\n"

In [63]:
np.arange(1,10,1)

# start,stop,step-size(by default is 1)
# start from any number and goes all the way upto, but not
# including stop index.
# start is inclusive and the end is exclusive.


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
" Zeros and Ones"

"Zeros:-\
Return a new array of given shape and type, filled with zeros\
gives 1D array"

'Zeros:-Return a new array of given shape and type, filled with zerosgives 1D array'

In [65]:
np.zeros(5)

# dot after 0 indicating that it's a floating point number.

array([0., 0., 0., 0., 0.])

In [66]:
type(0.)

float

In [67]:
np.zeros((4,5))

# passing a tuple can create matrix.
# (rows,columns)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [68]:
"""
Python numpy. ones() function returns a new array of
 given shape and data type, where the element's
 value is set to 1.
"""


"\nPython numpy. ones() function returns a new array of\n given shape and data type, where the element's \n value is set to 1.\n"

In [69]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [70]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
"""
Numpy allows you to perform operations that are broadcasted to
every single number on  the array.

Meaning , if i take my ones, and I add four,numpy will add
4 to each ones

this is not possible with normal python list.

for example if we multiply python list with any number
instead of performing operation it will print list number.

[1,1,1]*100 will print each 1 , 100 times

if we try to add [1,1,1]+100 will give an error.
can't concatenate a list to an integer because they are
two different data types

Numpy can do this. can perform any operation. add,multipy,divide

"""

"\nNumpy allows you to perform operations that are broadcasted to\nevery single number on  the array.\n\nMeaning , if i take my ones, and I add four,numpy will add\n4 to each ones\n\nthis is not possible with normal python list.\n\nfor example if we multiply python list with any number\ninstead of performing operation it will print list number.\n\n[1,1,1]*100 will print each 1 , 100 times\n\nif we try to add [1,1,1]+100 will give an error.\ncan't concatenate a list to an integer because they are \ntwo different data types\n\nNumpy can do this. can perform any operation. add,multipy,divide\n\n"

In [72]:
np.ones((5,5)) +4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [73]:
np.ones(5) *100

array([100., 100., 100., 100., 100.])

In [74]:
np.ones(10)/108

array([0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925926,
       0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925926])

In [75]:
"""
Create linearly spaces arrays that return evenly spaced numbers
over a specified interval,
A little different than arange method.

arange allow you to define the size of the step.
linspace allow you to define the number of steps.
linspace(0,1,20) : 20 evenly spaced numbers from 0 to 1 (inclusive).
arange(0, 10, 2) : however many numbers are needed to
go from 0 to 10 (exclusive)

arange return integers from a start, a stop and then a step size
NP linspace, is an inclusive start, an inclusive stop and then
we get to ask how many numbers we want
"""

'\nCreate linearly spaces arrays that return evenly spaced numbers\nover a specified interval,\nA little different than arange method.\n\narange allow you to define the size of the step.\nlinspace allow you to define the number of steps.\nlinspace(0,1,20) : 20 evenly spaced numbers from 0 to 1 (inclusive). \narange(0, 10, 2) : however many numbers are needed to\ngo from 0 to 10 (exclusive) \n\narange return integers from a start, a stop and then a step size\nNP linspace, is an inclusive start, an inclusive stop and then\nwe get to ask how many numbers we want\n'

In [76]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [77]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [78]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [79]:
"""
Identity matrix

NumPy eye() The eye() method creates a
2D array with 1s on the diagonal and 0s elsewhere.
"""

'\nIdentity matrix\n\nNumPy eye() The eye() method creates a \n2D array with 1s on the diagonal and 0s elsewhere.\n'

In [80]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
"""
Random number Numpy

The numpy. random. rand() function creates an array of
specified shapes fills it with random values and
generates random numbers with Numpy.

What is the difference between np random rand() and
np random randn()?

random. rand() produces random numbers from a
uniform distribution over the interval [0, 1),

while np. random. randn() generates random numbers
from a standard normal distribution.
Standard normal distribution has mean at zero and standard
deviation of 1.
"""

'\nRandom number Numpy\n\nThe numpy. random. rand() function creates an array of \nspecified shapes fills it with random values and \ngenerates random numbers with Numpy.\n\nWhat is the difference between np random rand() and \nnp random randn()?\n\nrandom. rand() produces random numbers from a \nuniform distribution over the interval [0, 1), \n\nwhile np. random. randn() generates random numbers\nfrom a standard normal distribution.\nStandard normal distribution has mean at zero and standard\ndeviation of 1.\n'

In [82]:
np.random.rand(4)

array([0.30725432, 0.79887295, 0.02267435, 0.64706719])

In [83]:
np.random.rand(4,5)

array([[0.76878283, 0.8926319 , 0.82475265, 0.56296713, 0.20633491],
       [0.51901626, 0.21315057, 0.70473498, 0.63847195, 0.71946907],
       [0.73001423, 0.81556019, 0.28162259, 0.07498055, 0.44002636],
       [0.87624011, 0.38040866, 0.38029327, 0.52024114, 0.99356318]])

In [84]:
np.random.randn(5)

array([-0.15832123,  0.25363011,  0.39819309,  0.10491144,  0.54180262])

In [85]:
# specify mean and sigma

np.random.normal(loc=10,scale=110)

#loc is mean and scale is Standard deviation.


-127.15497918648447

In [86]:
"""
Return random integers from low (inclusive) to high (exclusive).
Return random integers from the “discrete uniform”
distribution of the specified dtype in the “half-open”
interval [low, high). If high is None (the default),
then results are from [0, low).

It will return 1 random number/in range between high and low.
"""

'\nReturn random integers from low (inclusive) to high (exclusive). \nReturn random integers from the “discrete uniform” \ndistribution of the specified dtype in the “half-open” \ninterval [low, high). If high is None (the default), \nthen results are from [0, low).\n\nIt will return 1 random number/in range between high and low.\n'

In [87]:
np.random.randint(1,10)

4

In [88]:
np.random.randint(1,10,20)

array([9, 7, 5, 6, 5, 8, 6, 8, 5, 8, 4, 4, 2, 4, 6, 2, 1, 1, 9, 2])

In [89]:
# set a seed thats sets the random state that way the
# the random results can be actually reproduced
# will give each time same numbers
# number 42 does not have any particularly meaning
# its just an arbitrary number chosen.
# seed should be in the same cell otherwise it will give
# different numbers
np.random.seed(42)
np.random.randint(1,100,10)

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75])

In [90]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [91]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

**Array attributed and Methods**

In [92]:
arr=np.arange(25)
arr #arange array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [93]:
ranarr=np.random.randint(0,50,10)
ranarr #random array

array([41, 48, 32, 20, 22, 22, 10, 21, 27, 28])

In [94]:
arr.shape

(25,)

In [95]:
"""Reshape

Gives a new shape to an array without changing its data.

reshape() is used to create a new array of the same size
(as the original array) but of different desired dimensions.
resize() can create an array of larger size than the
original array.

.shape gives us shape of the array. but sometimes what if we do
not want 1D array may be we want 2D array.

Somthings we have to be careful is that we can't just choose
any arbitrary values for reshape. if for this example if
reshape(5,3) will give an arrray because array has 25 elements.
it will not fit. because it has space only for 15 elements.

"""

"Reshape\n\nGives a new shape to an array without changing its data.\n\nreshape() is used to create a new array of the same size \n(as the original array) but of different desired dimensions. \nresize() can create an array of larger size than the\noriginal array.\n\n.shape gives us shape of the array. but sometimes what if we do \nnot want 1D array may be we want 2D array.\n\nSomthings we have to be careful is that we can't just choose\nany arbitrary values for reshape. if for this example if\nreshape(5,3) will give an arrray because array has 25 elements.\nit will not fit. because it has space only for 15 elements.\n\n"

In [96]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [97]:
"""
max:-
The max() method returns the largest element of an
array along an axis.

min:-
Return the minimum of an array or minimum along an axis.

argmax:-
Returns the indices of the maximum values along an axis.
Input array. By default, the index is into the flattened
array, otherwise along the specified axis.

argmin:-

numpy. argmin (a, axis=None, out=None)[source] Returns the
 indices of the minimum values along an axis.

"""

'\nmax:-\nThe max() method returns the largest element of an\narray along an axis.\n\nmin:-  \nReturn the minimum of an array or minimum along an axis.\n\nargmax:-\nReturns the indices of the maximum values along an axis.\nInput array. By default, the index is into the flattened \narray, otherwise along the specified axis.\n\nargmin:-\n\nnumpy. argmin (a, axis=None, out=None)[source] Returns the\n indices of the minimum values along an axis.\n\n'

In [98]:
ranarr

array([41, 48, 32, 20, 22, 22, 10, 21, 27, 28])

In [99]:
ranarr.max()

48

In [100]:
ranarr.min()

10

In [101]:
#it does not tell index location

ranarr.argmax()

1

In [102]:
ranarr.argmin()

6

In [103]:
ranarr.dtype #type of data in random array.

dtype('int64')

#Numpy Index Selection

In [104]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
"""
bracket indexing and selection

Indexing:- Lets imagine we wanted to get 1 single value from
this 1D array. To do that, it works just like a normal
Python list.

"""

'bracket indexing and selection'

In [106]:
arr[3]

3

In [107]:
# values within range just like Python list
# It will not include last value.


arr[1:4]

array([1, 2, 3])

In [108]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [109]:
arr[:5]

array([0, 1, 2, 3, 4])

In [111]:
arr[5:]

#will not include 1st 5 elements.

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
"""
Broadcasting:-

NumPy arrays differ from normal python lists because they allow
broadcasting functions and operations across this.


"""

In [112]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
arr+100


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [114]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [116]:
arr**2

# this is general broadcasting

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [117]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
slice_arr=arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [120]:
# Broadcast a reassignment to the slice of this array.

slice_arr[:]=99


In [121]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [122]:
# slice_arr=arr[0:6] is directly pointing to the original array
# which means when we call original array
# 1st 5 elements are changed.
# So that's sort of broadcasting of reassignment based off a
# Slice like this.

arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [127]:
# if we do not want the original array affected
# we need to be explicit when a creating a copy
arr_copy=arr.copy()
print(arr_copy)

print(" ")

arr_copy[:]=1000
print(arr_copy)

print(" ")

print(arr)

[99 99 99 99 99 99  6  7  8  9 10]
 
[1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 1000]
 
[99 99 99 99 99 99  6  7  8  9 10]


In [ ]:
"""
Indexing and selection on 2D array
And then conditional selection based off some bullion condition.


"""

In [129]:
arr_2d=np.array([[5,10,15,],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [130]:
arr_2d.shape

(3, 3)

In [132]:
arr_2d[1]

array([20, 25, 30])

In [133]:
arr_2d[1][1]

25

In [134]:
arr_2d[1,1]

25

In [135]:
arr_2d[2,2]

45

In [136]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [138]:
arr_2d[:2] #1st two rows

array([[ 5, 10, 15],
       [20, 25, 30]])

In [139]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
"""
Conditional selection:-

It is a fundamental concept that directly translates to Pandas
and it allows us to use comparison operators to acutally grab
elements.

"""

In [140]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [141]:
#bullion comparison
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [142]:
bool_arr=arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [143]:
arr[bool_arr]

# it will only reutnr values where the index locations were true.


array([ 5,  6,  7,  8,  9, 10])

In [145]:
arr[arr>4]

# exact same thing in 1 step

array([ 5,  6,  7,  8,  9, 10])

# Numpy Operations

In [ ]:
"""
When we performing operations on NumPy its often on an element
by element basis where the operation is broadcasted across the
array.

When we try to divide by zero or infinity NumPy will actually
not produce a full error. Instead it will just produce a warning


"""

In [147]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [149]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [150]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [151]:
(arr+2)/10

array([0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1])

In [152]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [153]:
1/arr
#warning when we divide by zero.

<ipython-input-153-016353831300>:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [154]:
arr/arr

<ipython-input-154-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [155]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [156]:
np.log(arr)

<ipython-input-156-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [157]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [158]:
arr.sum()

45

In [159]:
arr.mean()

4.5

In [160]:
arr.max()

9

In [163]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr_2d)
print(arr_2d.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [164]:
arr_2d.sum()

78

In [166]:
arr_2d.sum(axis=0)

#sum of each column in 1D array

array([15, 18, 21, 24])

In [168]:
arr_2d.sum(axis=1)

#sum of each row in 1D array

array([10, 26, 42])